/* add wave -position end  sim:/processor/clk
add wave -position end  sim:/processor/reset
add wave -position end  sim:/processor/in_port
add wave -position end  sim:/processor/fetch_instruction_out
add wave -position end  sim:/processor/IFID_ALU_operation
add wave -position end  sim:/processor/IFID_imm
add wave -position end  sim:/processor/WRITE_BACK_DATA
add wave -position end  sim:/processor/MEMWB_OUT
add wave -position end  sim:/processor/EXMEM_OUT
add wave -position end  sim:/processor/IDEX_OUT
add wave -position 0  sim:/processor/IFID_OUT
add wave -position end  sim:/processor/ds/ALU_operation
add wave -position end  sim:/processor/ds/imm
add wave -position end  sim:/processor/es/ALU_Result
add wave -position end  sim:/processor/es/ALU_Operation
add wave -position end  sim:/processor/es/A
add wave -position end  sim:/processor/es/B
add wave -position 5  sim:/processor/es/Immediate_in
add wave -position 6  sim:/processor/es/RsrcData_in
add wave -position 7  sim:/processor/es/RdstData_in
add wave -position end  sim:/processor/ms/memory_addr
add wave -position end  sim:/processor/ms/SP_Addr
add wave -position end  sim:/processor/ms/SP_Addr_In
add wave -position end  sim:/processor/ms/SP_Addr_Out
add wave -position end  sim:/processor/ms/memory_addr
add wave -position end  sim:/processor/ms/memory_out
add wave -position 14  sim:/processor/ms/memory_in
add wave -position end  sim:/processor/wb/SP_data
add wave -position end  sim:/processor/wb/WB_data 
add wave -position end  sim:/processor/ms/dm/ram*/